
title: Minimal Blog
email: your-email@example.com
description: >-
 - Pages statics com Jekyll.
baseurl: "/minimal-blog" # the subpath of your site, e.g. /blog
url: "https://rodrigosilvaluz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: minimal
github_username:  "/minimal-blog"


# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:title
#plugins:

